-- SERIAL VS IDENTITY 

create table "users"(
	"user_id" SERIAL PRIMARY KEY,
	"user_name" VARCHAR
);
	
create table "users2"(
	"user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"user_name" VARCHAR
);

create table "users3"(
	"user_id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"user_name" VARCHAR
);

create table "users4"(
	"user_id" INTEGER GENERATED ALWAYS AS IDENTITY (start with 100 increment by 2) PRIMARY KEY,
	"user_name" VARCHAR
);

-- PRIMARY KEY COMPUESTA 


create table userDual (
	id1 int,
	id2 int,
	PRIMARY KEY(id1,id2)
);